-- 1. DML(DATA MANIPULATION LANGUAGE): 데이터 조작 언어
-- 데이터를 저장, 수정, 삭제하는 언어로 INSERT INTO, UPDATE SET, DELETE FROM이 존재한다.
-- DML은 트렌젝션을 완료하기위해 항상 COMMIT이나 ROLLBACK을 한다.
-- 1-1. INSERT INTO: 테이블에 데이터를 저장하는 명령어
-- 일부 컬럼에 대한 데이터를 저장
INSERT INTO EMP(ENO, ENAME, JOB, HDATE) VALUES ('9997', '장길산','설계',SYSDATE);
COMMIT;

SELECT *
	FROM EMP;

INSERT INTO EMP(ENO, ENAME, JOB, HDATE) VALUES ('9996', '임꺽정','개발',SYSDATE);
INSERT INTO EMP(ENO, ENAME, JOB, HDATE) VALUES ('9995', '홍길동','회계',SYSDATE);
INSERT INTO EMP(ENO, ENAME, JOB, HDATE) VALUES ('9994', '조병조','지원',SYSDATE);
INSERT INTO EMP(ENO, ENAME, JOB, HDATE) VALUES ('9993', '정도전','경영',SYSDATE);
-- COMMIT이 발생한 작업에 대해서는 ROLLBACK으로 취소 할 수 없다.
ROLLBACK;









